name: Develop (beta)

on:
  workflow_dispatch:
  push:
    branches:
      develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          source-url: https://nuget.pkg.github.com/toletus/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Set version number environment variable
        env:
          github_ref: ${{ github.ref }}
        run: |
          version='7.${{ github.run_number }}.${{ github.run_attempt }}'
           echo version=$version
           echo "version=$version" >> $GITHUB_ENV
      
      - name: Build with dotnet
        run: |
          dotnet build "src/Toletus.SM25/Toletus.SM25.csproj" --configuration Release -p:Version=${{ env.version }}

      - name: Create the Package
        run: |
          dotnet pack "src/Toletus.SM25/Toletus.SM25.csproj" --configuration Release /p:PackageVersion=${{ env.version }}-beta

      - name: Publish Toletus.SM25 on Nuget
        #run: dotnet nuget push "src/Toletus.SM25/bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/toletus/index.json --skip-duplicate
        run: dotnet nuget push "src/Toletus.SM25/bin/Release/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}

       